<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent><groupId>com.yupi</groupId><artifactId>smart-bi-modules</artifactId><version>0.0.1-SNAPSHOT</version></parent>
    <artifactId>bi-web</artifactId>
    <name>bi-web</name>
    <dependencies>
        <dependency><groupId>com.yupi</groupId><artifactId>bi-ai-runtime</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>com.yupi</groupId><artifactId>bi-common</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>com.yupi</groupId><artifactId>bi-infra</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>com.yupi</groupId><artifactId>bi-module-analysis-biz</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>com.yupi</groupId><artifactId>bi-module-user-biz</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>com.yupi</groupId><artifactId>bi-module-auth-biz</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>com.yupi</groupId><artifactId>bi-module-chart-biz</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>com.yupi</groupId><artifactId>bi-module-file-biz</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>com.yupi</groupId><artifactId>bi-module-dashboard-biz</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>com.yupi</groupId><artifactId>bi-module-report-biz</artifactId><version>${project.version}</version></dependency>
    </dependencies>
</project>
